################################################################
# Global configuration
################################################################
global:
  checkNewVersion: true
  sendAnonymousUsage: false

################################################################
# EntryPoints configuration
################################################################
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
    
  websecure:
    address: :443

################################################################
# API and dashboard configuration
################################################################
api:
  dashboard: true
  insecure: false

################################################################
# Ping configuration
################################################################
ping:
  entryPoint: web

################################################################
# Docker configuration backend
################################################################
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: proxy
    watch: true

################################################################
# HTTPS Configuration with Cloudflare DNS Challenge
################################################################
certificatesResolvers:
  cloudflare:
    acme:
      email: "travis.vas@gmail.com"
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
        delayBeforeCheck: 0

################################################################
# Log configuration
################################################################
log:
  level: DEBUG  # Temporarily set to DEBUG for troubleshooting

accessLog: {}